# Generated by Django 4.2 on 2026-03-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(verbose_name=255)),
                ('description', models.CharField(verbose_name=500)),
            ],
        ),
    ]
